# Generated by Django 4.1.4 on 2023-01-03 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/')),
                ('description', models.TextField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('ordering', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-ordering'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('ordering', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-ordering'],
            },
        ),
        migrations.CreateModel(
            name='ImageArticle',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/')),
                ('description', models.TextField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('ordering', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-ordering'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('ordering', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-ordering'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/')),
                ('description', models.TextField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category')),
            ],
            options={
                'ordering': ['-ordering'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.maincategory'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=400)),
                ('price', models.PositiveIntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/')),
                ('change', models.BooleanField(default=False)),
                ('give', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('premium', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False)),
                ('ordering', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.category')),
                ('color', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_color', to='articles.color')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_condition', to='articles.condition')),
                ('image_article', models.ManyToManyField(blank=True, related_name='article_image', to='articles.imagearticle')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.maincategory')),
                ('size', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_size', to='articles.size')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='articles.subcategory')),
                ('tag', models.ManyToManyField(blank=True, related_name='articles', to='articles.tag')),
            ],
        ),
    ]
